application:
  name: Warehouse Inventory Management
  host: 0.0.0.0
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  username: your-db-username
  password: your-db-password
  database_name: your-db-name